name: ssh-ssh
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: github
      run: git clone https://github.com/openwrt/openwrt
        cd openwrt
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
    - name: cd mkdir
      run: cd ~
            mkdir R6220
    - name: SctA2
      uses: P3TERX/debugger-action@master
