name: built_VM_openwrt19.07
on:
  push:
    branches:
      - VM_openwrt
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install softwares/enviroments
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig rsync
    - name: Clone source code/update feeds
      run: |
        git clone https://github.com/coolsnowwolf/openwrt
        cd openwrt
        ./scripts/feeds update -a
    - name: Re Upadte feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: menuconfig
      uses: P3TERX/debugger-action@main
# Image Target : Choose VMDK manually
    - name: Download package/dl
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: redownload pkg/dl
      run: |
        cd openwrt
        make download -j8
    - name: Build Target
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
    - name : Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: openwrt
        path: openwrt/bin
